FalconOrchestrator.Web/Models/ViewModels/WhitelistingViewModel.cs
//<Falcon Orchestrator provides automated workflow and response capabilities>
//    Copyright(C) 2016 CrowdStrike

//   This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as
//    published by the Free Software Foundation, either version 3 of the
//    License, or(at your option) any later version.

//   This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
//    GNU Affero General Public License for more details.

//    You should have received a copy of the GNU Affero General Public License
//    along with this program.If not, see<http://www.gnu.org/licenses/>.


using System.Collections.Generic;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using System.ComponentModel.DataAnnotations;


namespace FalconOrchestratorWeb.Models.ViewModels
{
    public class WhitelistingViewModel : IValidatableObject
    {
        public int WhitelistId { get; set; }
        public string Timestamp { get; set; }
        [Required(ErrorMessage="Creator is required, this is based off logged in username")]
        public string Creator { get; set; }
        [Required(ErrorMessage = "Reason for rule is required")]
        public string Reason { get; set; }
        public string Type { get; set; }
        [Required(ErrorMessage = "Type is required")]
        public int TypeId { get; set; }
        [Required(ErrorMessage = "Value is required")]

        [AllowHtml]
        public string Value { get; set; }
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.TypeId == 1 && !Regex.IsMatch(this.Value, @"\b(?:[a-fA-F0-9][\s]*){63}[a-fA-F0-9]\b"))
            {
                yield return new ValidationResult("Not a valid SHA256 hash format", new[] { "Value" });
            }
        }
    }
}

FalconOrchestrator.Web/Controllers/WhitelistingController.cs
//<Falcon Orchestrator provides automated workflow and response capabilities>
//    Copyright(C) 2016 CrowdStrike

//   This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as
//    published by the Free Software Foundation, either version 3 of the
//    License, or(at your option) any later version.

//   This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
//    GNU Affero General Public License for more details.

//    You should have received a copy of the GNU Affero General Public License
//    along with this program.If not, see<http://www.gnu.org/licenses/>.


using System;
using System.Web.Mvc;
using FalconOrchestratorWeb.Repository;
using FalconOrchestrator.DAL;
using FalconOrchestratorWeb.Models.ViewModels;
using System.Net;


namespace FalconOrchestratorWeb.Controllers
{
    [Authorize]
    public class WhitelistingController : BaseController
    {
        private WhitelistingRepository repo = new WhitelistingRepository();

        [HttpGet]
        public ActionResult Index()
        {
            return View(repo.GetList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            FalconOrchestratorDB db = new FalconOrchestratorDB();
            ViewBag.TypeId = new SelectList(db.WhitelistTypes, "WhitelistTypeId", "Type", String.Empty);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WhitelistingViewModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    repo.Create(model);
                    RefreshDetections();
                    return RedirectToAction("Index");
                }

                catch (Exception e)
                {
                    ModelState.AddModelError(String.Empty, e.Message);
                }
            }

            FalconOrchestratorDB db = new FalconOrchestratorDB();
            ViewBag.TypeId = new SelectList(db.WhitelistTypes, "WhitelistTypeId", "Type", String.Empty);
            return View(model);
        }


        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            repo.Delete(id);
            Response.StatusCode = 200;
            return new EmptyResult();

        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            FalconOrchestratorDB db = new FalconOrchestratorDB();
            WhitelistingViewModel model = repo.Get(id);
            ViewBag.TypeId = new SelectList(db.WhitelistTypes, "WhitelistTypeId", "Type", model.TypeId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WhitelistingViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repo.Update(model);
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(String.Empty, e.Message);
                }
            }

            FalconOrchestratorDB db = new FalconOrchestratorDB();
            ViewBag.TypeId = new SelectList(db.WhitelistTypes, "WhitelistTypeId", "Type", model.Type);
            return View(model);

        }

    }
}

FalconOrchestrator.Web/Views/Whitelisting/Create.cshtml
@model FalconOrchestratorWeb.Models.ViewModels.WhitelistingViewModel

@{
    ViewBag.Title = "Whitelisting - Create";
}
<div class="container box-shadow">
@using (Html.BeginForm("Create", "Whitelisting", FormMethod.Post))
{
    <div class="form-horizontal">
        @Html.AntiForgeryToken()
        @Html.Hidden("Creator", User.Identity.Name)
        <span class="fa fa-2x fa-edit"></span>
        <span class="header">Create Whitelist Rule</span>
        <hr />
        @Html.ValidationSummary()
        <p>
            Note that once changes are applied, events will be updated retroactively.  Once a value has been included in the whitelist,
            all past and future events matching the criteria will automatically be marked
            in a <strong>WHITELISTED</strong> status.
        </p>
        <br />
        <div class="well">
            <div class="form-group">
                @Html.LabelFor(Model => Model.Type, "Type:", new { @class = "control-label col-2" })
                <div class="col-10">
                    @Html.DropDownList("TypeId", null, String.Empty, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TypeId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.Value, "Value:", new { @class = "control-label col-2" })
                <div class="col-10">
                    @Html.TextBoxFor(model => model.Value, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Value)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Reason, "Reason:", new { @class = "control-label col-2" })
                <div class="col-10">
                    @Html.TextAreaFor(model => model.Reason, new { @rows = "8", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Reason)
                </div>
            </div>
            <div class="form-group">
                <div class="form-align">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-save"></i> Save
                    </button>
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}
</div>


@section scripts{
}


@section styles{

}

FalconOrchestrator.Web/Views/Whitelisting/Edit.cshtml
@model FalconOrchestratorWeb.Models.ViewModels.WhitelistingViewModel

@{
    ViewBag.Title = "Whitelisting - Edit";
}
<div class="container box-shadow">
 @using (Html.BeginForm("edit", "whitelisting", FormMethod.Post))
 {
    <div class="form-horizontal">
        @Html.AntiForgeryToken()
        @Html.Hidden("WhitelistId", Model.WhitelistId)
        @Html.Hidden("Creator", User.Identity.Name)

        <span class="fa fa-2x fa-edit"></span>
        <span class="header">Edit Whitelist Rule @Model.WhitelistId</span>
        <hr />
        @Html.ValidationSummary()
        <p>
            When editing a whitelist rule, only the reason field can be changed.  If you need to change the type or value, delete this rule
            and create a new one.
        </p>
        <br />
        <div class="well">
            <div class="form-group">
                @Html.LabelFor(x => Model.Type, "Type:", new { @class = "control-label col-2" })
                <div class="col-10">
                    @Html.DropDownList("TypeId", null, String.Empty, new { @class = "form-control", @disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.TypeId)
                    @Html.HiddenFor(x => x.TypeId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => Model.Value, "Value:", new { @class = "control-label col-2" })
                <div class="col-10">
                    @Html.TextBoxFor(model => model.Value, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.Value)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => Model.Reason, "Reason:", new { @class = "control-label col-2" })
                <div class="col-10">
                    @Html.TextAreaFor(x => Model.Reason, new { @rows = "8", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Reason)
                </div>
            </div>
            <div class="form-group">
                <div class="form-align">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-save"></i> Save
                    </button>
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
 }   
</div>

@section scripts{
}


@section styles{

}

FalconOrchestrator.Web/Views/Whitelisting/Index.cshtml
@model List<FalconOrchestratorWeb.Models.ViewModels.WhitelistingViewModel>

@{
    ViewBag.Title = "Whitelisting";
}

<div class="container">
    <h1>Whitelisting</h1>
    <hr />
    <p>
        Let's face it, every system will eventually result in some false positives, whether it be legitimate software that looks like malware
        or administrative activity that is detected as suspicious.  This provides a self-service functionality to whitelist events based on a number of different variables.
        File name, file path and command line filtering also support regular expressions.  When a detection event is whitelisted, it will be set to a status indicating so.
        This allows responders to not waste time reviewing the event and also allows them to identify false positive rates through reporting.
    </p>
    <br />
    <p>
        <a href="/whitelisting/create" class="btn btn-success" id="create"><i class="fa fa-edit"></i> Create</a>
    </p>
    <br />
    <table id="datatableWR" class="table table-striped table-bordered table-hover dt-responsive">
        <thead>
            <tr>
                <th>
                    Timestamp
                </th>
                <th>
                    Creator
                </th>
                <th>
                    Type
                </th>
                <th>
                    Value
                </th>
                <th>
                    Reason
                </th>
                <th class="center-align">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => item.Timestamp)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Creator)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Value)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Reason)
                    </td>
                    <td class="center-align">
                        <a class="btn btn-default btn-success btn-sm" href="/whitelisting/edit/@item.WhitelistId"><i class="fa fa-edit"></i> Edit</a>
                        <a class="btn btn-default btn-danger btn-sm" href="#" onclick="DeleteRecord(@item.WhitelistId);"><i class="fa fa-trash-o"></i> Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/jquery.dataTables.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/dataTables.bootstrap.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/dataTables.responsive.js")"></script>

    <script>
        $(document).ready(function () {
            $('#datatableWR').dataTable({
                "order": [[0, "desc"]],
                "pagingType": "simple_numbers"
            });   
        });

        function DeleteRecord(id)
        {
            $.ajax({
                url: '/whitelisting/delete/' + id,
                type: 'POST',
                success: function()
                {
                    location.reload();
                }
            });
        }
    </script>
}


@section styles{
    <link href="@Url.Content("~/Content/DataTables-1.10.4/css/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/DataTables-1.10.4/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />
}