FalconOrchestrator.Web/Areas/Admin/Models/ConfigurationViewModels.cs
//<Falcon Orchestrator provides automated workflow and response capabilities>
//    Copyright(C) 2016 CrowdStrike

//   This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as
//    published by the Free Software Foundation, either version 3 of the
//    License, or(at your option) any later version.

//   This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
//    GNU Affero General Public License for more details.

//    You should have received a copy of the GNU Affero General Public License
//    along with this program.If not, see<http://www.gnu.org/licenses/>.


using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;


namespace FalconOrchestratorWeb.Areas.Admin.Models
{
    public class ConfigurationItemsViewModel
    {
        public LDAPConfigViewModel LDAP { get; set; }
        public FalconStreamingAPIConfigViewModel FalconStream { get; set; }
        public FalconForensicsConfigViewModel FalconForensics { get; set; }
        public EmailConfigViewModel Email { get; set; }
        public FalconQueryAPIConfigViewModel FalconQuery { get; set; }
        public ETLRulesViewModel ETLRules { get; set; }
    }


    public class LDAPConfigViewModel
    {
        [Required(ErrorMessage = "A server hostname or IP address is required")]
        public string Server { get; set; }
        [Required(ErrorMessage = "A Username is required")]
        public string Username { get; set; }
        [Required(ErrorMessage = "A Password is required")]
        public string Password { get; set; }
        [Required(ErrorMessage = "A Description is required")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Days valid is required")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Days valid must be a number")]
        public int DaysValid { get; set; }
    }

    public class ETLRulesViewModel : IValidatableObject
    {
        public Boolean Whitelisting { get; set; }
        public Boolean ADLookup { get; set; }
        public Boolean Taxonomize { get; set; }
        public Boolean DNSLookup { get; set; }
        public Boolean AssignResponder{ get; set; }
        public Boolean Notification { get; set; }
        public string NotificationThreshold { get; set; }
        public List<SelectListItem> SeverityList
        {
            get
            {
                List<SelectListItem> items = new List<SelectListItem>();
                items.Add(new SelectListItem() { Text = "Informational", Value = "1" });
                items.Add(new SelectListItem() { Text = "Low", Value = "2" });
                items.Add(new SelectListItem() { Text = "Medium", Value = "3" });
                items.Add(new SelectListItem() { Text = "High", Value = "4" });
                items.Add(new SelectListItem() { Text = "Critical", Value = "5" });
                return items;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.Notification == true && this.NotificationThreshold == null)
            {
                yield return new ValidationResult("A notification threshold must be defined", new[] { "NotificationThreshold" });
            }
        }
    }

    public class FalconStreamingAPIConfigViewModel
    {
        [Url(ErrorMessage = "Not a valid URL format")]
        [Required(ErrorMessage = "API URL is required")]
        public string Url { get; set; }
        [Required(ErrorMessage = "API Username is required")]
        public string Uuid { get; set; }
        [Required(ErrorMessage = "API Password required")]
        public string Key { get; set; }

        public string Offset { get; set; }
    }

    public class FalconQueryAPIConfigViewModel
    {
        [Url(ErrorMessage = "Not a valid URL format")]
        [Required(ErrorMessage = "API URL is required")]
        public string Url { get; set; }
        [Required(ErrorMessage = "API Username is required")]
        public string Username { get; set; }
        [Required(ErrorMessage = "API Password required")]
        public string Password { get; set; }
    }


    public class FalconForensicsConfigViewModel
    {
        [Required(ErrorMessage = "Username is required")]
        public string Username { get; set; }

        public string Domain { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Zip password is required")]
        public string ZipPassword { get; set; }
    }

    public class EmailConfigViewModel
    {
        [Required(ErrorMessage = "Server Hostname or IP is required")]
        public string Server { get; set; }

        [Required(ErrorMessage = "Port  is required")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Port must be numeric")]
        public string Port { get; set; }

        [Required(ErrorMessage = "Username is required")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Alert subject is required")]
        public string AlertSubject { get; set; }

        [Required(ErrorMessage = "Alert template path is required")]
        public string AlertTemplatePath { get; set; }

        [Required(ErrorMessage = "Ticket subject is required")]
        public string TicketSubject { get; set; }

        [Required(ErrorMessage = "Ticket template path is required")]
        public string TicketTemplatePath { get; set; }

        [Required(ErrorMessage = "SSL is required")]
        public Boolean SSL { get; set; }

        [EmailAddress(ErrorMessage="Not a valid email address format")]
        [Required(ErrorMessage = "Sender email address is required")]
        public string SenderAddress { get; set; }

        [Required(ErrorMessage = "Team email address is required")]
        public string TeamAddress { get; set; }

        [Required(ErrorMessage = "Home URL is required")]
        public string HomeURL { get; set; }

    }


}

FalconOrchestrator.Web/Areas/Admin/Controllers/ConfigurationController.cs
//<Falcon Orchestrator provides automated workflow and response capabilities>
//    Copyright(C) 2016 CrowdStrike

//   This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as
//    published by the Free Software Foundation, either version 3 of the
//    License, or(at your option) any later version.

//   This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
//    GNU Affero General Public License for more details.

//    You should have received a copy of the GNU Affero General Public License
//    along with this program.If not, see<http://www.gnu.org/licenses/>.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FalconOrchestratorWeb.Areas.Admin.Models;
using FalconOrchestratorWeb.Areas.Admin.Repository;

namespace FalconOrchestratorWeb.Areas.Admin.Controllers
{
    public class ConfigurationController : Controller
    {
        private readonly ConfigurationRepository repo = new ConfigurationRepository();

        [HttpGet]
        public ActionResult Index()
        {
             ConfigurationItemsViewModel model = repo.MapExisitingValues();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LDAPSettings(LDAPConfigViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateLDAPSettings(model);
                    return PartialView("_Success", "Active Directory settings have been updated");
                }
                catch (Exception e)
                {
                    return PartialView("_Error", e.Message);
                }
            }

            List<string> errors = ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors).Select(x => x.ErrorMessage).ToList();
            return PartialView("_ValidationError", errors);
          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmailSettings(EmailConfigViewModel model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateEmailSettings(model);
                    return PartialView("_Success", "Email settings have been updated");
                }
                catch (Exception e)
                {
                    return PartialView("_Error", e.Message);
                }
            }

            List<string> errors = ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors).Select(x => x.ErrorMessage).ToList();
            return PartialView("_ValidationError", errors);
                   
        }

        [HttpPost]
        public ActionResult FalconStreamingAPISettings(FalconStreamingAPIConfigViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateFalconStreamingAPISettings(model);
                    return PartialView("_Success", "Falcon Streaming API settings have been updated");
                }
                catch (Exception e)
                {
                    return PartialView("_Error", e.Message);
                }
            }

            List<string> errors = ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors).Select(x => x.ErrorMessage).ToList();
            return PartialView("_ValidationError", errors);
          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FalconForensicsSettings(FalconForensicsConfigViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateFalconForensicsSettings(model);
                    return PartialView("_Success", "Forensics settings have been updated");
                }
                catch (Exception e)
                {
                    return PartialView("_Error", e.Message);
                }
            }

            List<string> errors = ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors).Select(x => x.ErrorMessage).ToList();
            return PartialView("_ValidationError", errors);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FalconQueryAPISettings(FalconQueryAPIConfigViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateFalconQueryAPISettings(model);
                    return PartialView("_Success", "Falcon Query API settings have been updated");
                }
                catch (Exception e)
                {
                    return PartialView("_Error", e.Message);
                }
            }
            List<string> errors = ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors).Select(x => x.ErrorMessage).ToList();
            return PartialView("_ValidationError", errors);          
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public PartialViewResult ETLRules(ETLRulesViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repo.UpdateETLRules(model);
                    return PartialView("_Success", "Processing rules have been updated");
                }
                catch (Exception e)
                {
                    return PartialView("_Error", e.Message);
                }
            }

            List<string> errors = ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors).Select(x => x.ErrorMessage).ToList();
            return PartialView("_ValidationError", errors);          
        }

    }
}

FalconOrchestrator.Web/Areas/Admin/Views/Configuration/_ETLRules.cshtml
@model FalconOrchestratorWeb.Areas.Admin.Models.ETLRulesViewModel
@using (Ajax.BeginForm("ETLRules", "Configuration", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result-rules" }))
{
    @Html.AntiForgeryToken()
    <div id="result-rules" class="row col-12">
    </div>
    <div class="row col-12">
        <h3>Processing Rules</h3>
        <br />
        <p>
            These settings are used by the Falcon Orchestrator client service.  If a rule is enabled, the associated action will be performed against each detection event consumed
            from the Falcon Streaming API.  Ensure that the necessary service account credentials are configured if you are enabling a rule that requires one.
        </p>
        <br />
    </div>
    <table>
        <tbody>
            <tr>
                <td class="config-label"><h4>Assign Responder</h4></td>
                <td class="config-value">@Html.CheckBoxFor(model => model.AssignResponder, new { data_toggle = "toggle", data_width = 150, data_on = "Enabled", data_off = "Disabled"})</td>
            </tr>
            <tr>
                <td class ="config-label"><h4>DNS Resolution</h4></td>
                <td class="config-value">@Html.CheckBoxFor(model => model.DNSLookup, new { data_toggle = "toggle", data_width = 150, data_on = "Enabled", data_off = "Disabled"})</td>
            </tr>
            <tr>
                <td class="config-label"><h4>Active Directory Lookup</h4></td>
                <td class="config-value">@Html.CheckBoxFor(model => model.ADLookup, new { data_toggle = "toggle", data_width = 150, data_on = "Enabled",data_off="Disabled"})</td>
            </tr>
            <tr>
                <td class="config-label"><h4>Taxonomize</h4></td>
                <td class="config-value">@Html.CheckBoxFor(model => model.Taxonomize, new { data_toggle = "toggle", data_width = 150, data_on = "Enabled", data_off = "Disabled"})</td>
            </tr>
            <tr>
                <td class ="config-label"><h4>Whitelisting</h4></td>
                <td class="config-value">@Html.CheckBoxFor(model => model.Whitelisting, new { data_toggle = "toggle", data_width = 150, data_on = "Enabled", data_off = "Disabled"})</td>
            </tr>
            <tr>
                <td class="config-label"><h4>Notification</h4></td>
                <td class="config-value">@Html.CheckBoxFor(model => model.Notification, new { data_toggle = "toggle", data_width = 150, data_on = "Enabled", data_off = "Disabled"})</td>
            </tr>
            <tr>
                <td class="config-label"><h4>Notification Threshold</h4></td>
                <td class="config-value">@Html.DropDownListFor(x => x.NotificationThreshold, Model.SeverityList, String.Empty, new { @class = "form-control" })</td>
            </tr>
        </tbody>
    </table>
    <div class="row col-8" style="margin-top:10px;">
        <div class="form-group">
            <div class="col-md-offset-6">
                <button type="submit" class="btn btn-default btn-success">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
    </div>
}

FalconOrchestrator.Web/Areas/Admin/Views/Configuration/_EmailSettings.cshtml
@model FalconOrchestratorWeb.Areas.Admin.Models.EmailConfigViewModel
@using (Ajax.BeginForm("EmailSettings", "Configuration", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result-email" }))
{
    @Html.AntiForgeryToken()
    <div id="result-email" class="row col-12">
    </div>
    <div class="row col-12">
        <h3>Email Configuration</h3>
        <br />
        <p>
            The settings below are required to integrate with your exchange environment and allow for
            automatic email notifications used by various components of the application.
        </p>
        <br />
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-server"></i> Server</span>
                @Html.TextBoxFor(model => model.Server, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-cog"></i> Port</span>
                @Html.TextBoxFor(model => model.Port, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"></i> Username</span>
                @Html.TextBoxFor(model => model.Username, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i> Password</span>
                @Html.PasswordFor(model => model.Password, new { @class = "form-control"})
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user-secret"></i> SSL</span>
                @Html.CheckBoxFor(model => model.SSL, new { @class = "form-checkbox" })
            </div>
        </div>
    </div>
    <div class="row col-12">
        <h3>Ticketing</h3>
        <br />
        <p>
            These settings are used for any email notifications that are sent as part of the ticketing module.
        </p>
        <br />
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-font"></i> Subject</span>
                @Html.TextBoxFor(model => model.TicketSubject, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-folder-open"></i> Template</span>
                @Html.TextBoxFor(model => model.TicketTemplatePath, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-12">
        <h3>Alerts</h3>
        <br />
        <p>
            These settings are used for any email notifications as part of the Detections module. Under Processing Rules configuration, you must enable
            notifications and set a notification severity threshold.
        </p>
        <br />
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-font"></i> Subject</span>
                @Html.TextBoxFor(model => model.AlertSubject, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-folder-open"></i> Template</span>
                @Html.TextBoxFor(model => model.AlertTemplatePath, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-12">
        <h3>Notification Contacts</h3>
        <br />
        <p>
            The team email address supplied below will be CC'd on all email notifications including new detection events and
            remediations tickets. In both fields, you can supply multiple email addresses or distribution lists by delimiting addresses with a semi-colon.
            The sender email address is what will be used by the system for all notifications.
        </p>
        <br />
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope"></i> Sender</span>
                @Html.TextBoxFor(model => model.SenderAddress, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope"></i> Team</span>
                @Html.TextBoxFor(model => model.TeamAddress, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-globe"></i> Home URL</span>
                @Html.TextBoxFor(model => model.HomeURL, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8" style="margin-top:10px;">
        <div class="form-group">
            <div class="col-md-offset-6">
                <button type="submit" class="btn btn-default btn-success">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
    </div>
}

FalconOrchestrator.Web/Areas/Admin/Views/Configuration/_FalconForensics.cshtml
@model FalconOrchestratorWeb.Areas.Admin.Models.FalconForensicsConfigViewModel
@using (Ajax.BeginForm("FalconForensicsSettings", "Configuration", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result-forensics" }))
{
    @Html.AntiForgeryToken()
    <div id="result-forensics" class="row col-12">
    </div>
    <div class="row col-12">
        <h3>Forensics Service Account</h3>
        <br />
        <p>
            Provide credentials for the privileged service account that will be used to connect to remote systems for live forensic analysis.
            This account should be well guarded, as it will have administrative access to all in-scope endpoints.
        </p>
        <br />
    </div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i> Username</span>
            @Html.TextBoxFor(model => model.Username,new { @class = "form-control"})
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i> Domain</span>
            @Html.TextBoxFor(model => model.Domain, new { @class = "form-control" })
        </div>
    </div>
</div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i> Password</span>
                @Html.PasswordFor(model => model.Password, new {@class = "form-control"})
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i> ZIP Password</span>
                @Html.PasswordFor(model => model.ZipPassword, new { @class = "form-control" })
            </div>
        </div>
    </div>
<br />
<div class="row col-8" style="margin-top:10px;">
    <div class="form-group">
        <div class="col-md-offset-6">
            <button type="submit" class="btn btn-default btn-success">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    </div>
</div>
}

FalconOrchestrator.Web/Areas/Admin/Views/Configuration/_FalconQueryApi.cshtml
@model FalconOrchestratorWeb.Areas.Admin.Models.FalconQueryAPIConfigViewModel
@using (Ajax.BeginForm("FalconQueryAPISettings", "Configuration", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result-query" }))
{
    @Html.AntiForgeryToken()
    <div id="result-query" class="row col-12">
    </div>
    <div class="row col-12">
        <h3>Falcon Query API Account</h3>
        <br />
        <p>
            Provide URL and credentials for your Falcon Host Query API account.  This enables functionality to manage indicators stored in the platform for automated detections.
        <p />
        <br />
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-globe"></i> URL</span>
                @Html.TextBoxFor(model => model.Url, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"></i> Username</span>
                @Html.TextBoxFor(model => model.Username, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row col-8">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i> Password</span>
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <br />
    <div class="row col-8" style="margin-top:10px;">
        <div class="form-group">
            <div class="col-md-offset-6">
                <button type="submit" class="btn btn-default btn-success">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
    </div>
}

FalconOrchestrator.Web/Areas/Admin/Views/Configuration/_FalconStreamingApi.cshtml
@model FalconOrchestratorWeb.Areas.Admin.Models.FalconStreamingAPIConfigViewModel
@using (Ajax.BeginForm("FalconStreamingAPISettings", "Configuration", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result-falconstream" }))
{
    @Html.AntiForgeryToken()
    <div id="result-falconstream" class="row col-12">
    </div>
    <div class="row col-12">
        <h3>Falcon Streaming API Account</h3>
        <br />
        <p>
            Provide the URL and credentials for your Falcon Host Streaming API account.  This is used by the client service which connects to the
            Streaming API containing all detections data.  Your credentials can be found in the Falcon Host UI People App.
        </p>
        <br />
    </div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-globe"></i> URL</span>
            @Html.TextBoxFor(model => model.Url, new { @class = "form-control" })
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i> UUID</span>
            @Html.TextBoxFor(model => model.Uuid, new { @class = "form-control" })
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-key"></i> Key</span>
            @Html.PasswordFor(model => model.Key, new { @class = "form-control"})
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-bookmark"></i> Offset</span>
            @Html.TextBoxFor(model => model.Offset, new { @class = "form-control" })
        </div>
    </div>
</div>
<br />
<div class="row col-8" style="margin-top:10px;">
    <div class="form-group">
        <div class="col-md-offset-6">
            <button type="submit" class="btn btn-default btn-success">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    </div>
</div>
}

FalconOrchestrator.Web/Areas/Admin/Views/Configuration/_LDAP.cshtml
@model FalconOrchestratorWeb.Areas.Admin.Models.LDAPConfigViewModel
@using (Ajax.BeginForm("LDAPSettings", "Configuration", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "result-ldap" }))
{
    @Html.AntiForgeryToken()
    <div id="result-ldap" class="row col-12">
    </div>
    <div class="row col-12">
        <h3>Active Directory Configuration</h3>
        <br />
        <p>
            The below settings are required to integrate with your LDAP server to automatically obtain
            user account metadata, defining taxonomies via OU's or groups and performing account containment. A server
            DNS name or IP address and credentials to access the LDAP server are required.  The description field
            is used to define the message that is added to an AD user account's description field when a containment action
            is taken.  This provides a written explanation for why the account has been modified.  The expiration timer
            determines how long a cached copy of the account metadata is considered valid.  If the timestamp on the account record
            execeeds this timer, a new lookup against Active Directory is made.
        </p>
        <br />
    </div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-server"></i> Server</span>
            @Html.TextBoxFor(model => model.Server, new { @class = "form-control" })
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user"></i> Username</span>
            @Html.TextBoxFor(model => model.Username, new { @class = "form-control"})
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-key"></i> Password</span>
            @Html.PasswordFor(model => model.Password, new { @class = "form-control"})
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-font"></i> Description</span>
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
        </div>
    </div>
</div>
<div class="row col-8">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-clock-o"></i> Days Valid</span>
            @Html.TextBoxFor(model => model.DaysValid, new { @class = "form-control" })
        </div>
    </div>
</div>
<br />
<div class="row col-8" style="margin-top:10px;">
    <div class="form-group">
        <div class="col-md-offset-6">
            <button type="submit" class="btn btn-default btn-success">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    </div>
</div>
}