FalconOrchestrator.Web/Areas/Forensics/Controllers/SystemRestoreController.cs
//<Falcon Orchestrator provides automated workflow and response capabilities>
//    Copyright(C) 2016 CrowdStrike

//   This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as
//    published by the Free Software Foundation, either version 3 of the
//    License, or(at your option) any later version.

//   This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
//    GNU Affero General Public License for more details.

//    You should have received a copy of the GNU Affero General Public License
//    along with this program.If not, see<http://www.gnu.org/licenses/>.

using System;
using System.Collections.Generic;
using System.Web.Mvc;
using FalconOrchestratorWeb.Controllers;
using FalconOrchestrator.Forensics;
using FalconOrchestratorWeb.Areas.Forensics.Models;


namespace FalconOrchestratorWeb.Areas.Forensics.Controllers
{
    public class SystemRestoreController : BaseController
    {
        private static List<SystemRestorePoint> points;

        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult RestorePoints(AssetViewModel viewModel)
        {
            try
            {
                PSRemoting psr = new PSRemoting(viewModel.ComputerName, config.FALCON_FORENSICS_USERNAME, config.FALCON_FORENSICS_PASSWORD, config.FALCON_FORENSICS_DOMAIN);
                SystemRestore restore = new SystemRestore(psr);
                points = restore.GetRestorePoints();
                return PartialView("_RestorePoints", points);
            }
            catch (Exception e)
            {
                return PartialView("_Error", e.Message);
            }
        }

        public PartialViewResult MountShadowCopy(string computerName, string timestamp)
        {
            try
            {
                PSRemoting psr = new PSRemoting(computerName, config.FALCON_FORENSICS_USERNAME, config.FALCON_FORENSICS_PASSWORD, config.FALCON_FORENSICS_DOMAIN);
                SystemRestore restore = new SystemRestore(psr);
                ShadowCopy copy = restore.GetShadowCopyByTime(Convert.ToDateTime(timestamp));
                restore.MountShadowCopyVolume(copy.DeviceObject + @"\");
                return BrowserRefresh(computerName, @"C:\shadow", copy.DeviceObject);

            }
            catch (Exception e)
            {
                Response.StatusCode = 500;
                return PartialView("_Error", e.Message);
            }
        }

        public PartialViewResult BrowserRefresh(string computerName, string path, string deviceObject)
        {
            try
            {
                PSRemoting psr = new PSRemoting(computerName, config.FALCON_FORENSICS_USERNAME, config.FALCON_FORENSICS_PASSWORD, config.FALCON_FORENSICS_DOMAIN);
                FileSystemBrowser browser = new FileSystemBrowser(psr);
                List<FileMetadata> model = browser.GetDirectoryContent(path);
                ViewBag.DeviceObject = deviceObject.Replace("\\", "\\\\");
                ViewBag.Path = path;
                ViewBag.ComputerName = computerName;
                return PartialView("~/Areas/Forensics/Views/SystemRestore/_ShadowCopyData.cshtml", model);
            }
            catch (Exception e)
            {
                Response.StatusCode = 500;
                return PartialView("_Error", e.Message);
            }
        }

        public PartialViewResult RecoverFile(string computerName, string source, string attributes)
        {
            try
            {
                PSRemoting psr = new PSRemoting(computerName, config.FALCON_FORENSICS_USERNAME, config.FALCON_FORENSICS_PASSWORD, config.FALCON_FORENSICS_DOMAIN);
                FileSystemBrowser browser = new FileSystemBrowser(psr);
                string destination = source.Replace(@"\shadow", "");

                if (attributes.Contains("Directory"))
                    source += @"\*";
                browser.CopyFile(source, destination);
                return PartialView("_Success", source + " has been successfully recovered");
            }
            catch (Exception e)
            {
                Response.StatusCode = 500;
                return PartialView("_Error", e.Message);
            }
        }

        public PartialViewResult ExecuteRestore(string computerName, string sequenceNumber)
        {
            try
            {
                PSRemoting psr = new PSRemoting(computerName, config.FALCON_FORENSICS_USERNAME, config.FALCON_FORENSICS_PASSWORD, config.FALCON_FORENSICS_DOMAIN);
                SystemRestore restore = new SystemRestore(psr);
                restore.RestoreSystem(sequenceNumber);
                return PartialView("_Success", "Restore has been successfully initialized on host " + computerName);
            }
            catch (Exception e)
            {
                return PartialView("_Error", e.Message);
            }
        }

    }
}

FalconOrchestrator.Web/Areas/Forensics/Views/SystemRestore/Index.cshtml
@model FalconOrchestratorWeb.Areas.Forensics.Models.AssetViewModel
@using (Ajax.BeginForm("RestorePoints", "SystemRestore", new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "restore-points" }))
{
    <div class="container">
        <h1>System Restore</h1>
        <br />
        <p>
            When a host is compromised, a common remedial action is to roll back the system to a
            point in time prior to the incident occuring. This can be achieved using the System Restore module.
            To begin, specify a target hostname or IP address. From there you will need to select a restore point from the
            provided list. You can then choose to restore the hosts configuration settings and/or to recover data that was backed up
            as part of the restore point.  
           
        </p>

        <hr />
        <div id="responseMessages"></div>
        <div class="well">
            <div class="form-horizontal">
                <div class="row">
                    @Html.Label("Computer", new { @class = "control-label col-2" })
                    <div class="col col-4">
                        @Html.TextBoxFor(x => x.ComputerName, new { @class = "form-control", @id = "targetComputerName" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default btn-success">
                            <i class="fa fa-search"></i> Search
                        </button>
                        <span id="execute-restore"></span>
                        <span id="recover-data"></span>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div id="restore-points"></div>
        <div id="shadow-storage"></div>
    </div>
}

FalconOrchestrator.Web/Areas/Forensics/Views/SystemRestore/_RecoverModal.cshtml
<div id="recoverModal" class="modal fade" data-backdrop="static" data-keyboard="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i></button>
                <h4 class="modal-title">Action Confirmation</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <p class="col-12">
                        <i class="fa fa-exclamation-triangle"></i>
                        <strong> WARNING:</strong> Are you sure you want to initiate a data recovery? This will mount the shadow copy backup to the file
                        system and allow you to select which files you want to recover.  This will not automatically start recovering files.
                    </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <input id="recover-confirmation-submit" type="submit" value="Yes" class="btn btn-default btn-primary" data-dismiss="modal" />
            </div>
        </div>
    </div>
</div>
<script>
    $('#recover-confirmation-submit').click(function () {
        var $computerName = $('#targetComputerName').val();
        var $datetime = $.trim($('table > tbody > tr.active >td:eq(0)').text());
            $.ajax({
                url: '@Url.Content("~/SystemRestore/MountShadowCopy")',
                data: {
                    'computerName': $computerName,
                    'timestamp': $datetime
                },
                success: function (result) {
                    $('#shadow-storage').html(result);
                },
                error: function(result)
                {
                    $('#responseMessages').html(result.responseText);
                    $('html, body').animate({ scrollTop: 0 }, 'fast');
                }
            })
    });
</script>

FalconOrchestrator.Web/Areas/Forensics/Views/SystemRestore/_RestoreModal.cshtml
<div id="restoreModal" class="modal fade" data-backdrop="static" data-keyboard="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i></button>
                <h4 class="modal-title">Action Confirmation</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <p class="col-12">
                        <i class="fa fa-exclamation-triangle"></i>
                        <strong> WARNING:</strong> Are you sure you want to initiate a system restore?  This action cannot be undone once applied. This will
                        restore operating system files, system settings and program files only.  To recover user data files, click the Recover option.
                    </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <input id="restore-confirmation-submit" type="submit" value="Yes" class="btn btn-default btn-primary" data-dismiss="modal" />
            </div>
        </div>
    </div>
</div>
<script>
    $('#restore-confirmation-submit').click(function () {
        var $computerName = $('#targetComputerName').val();
        var $sequenceNumber = $.trim($('table > tbody > tr.active >td:eq(2)').text());

            $.ajax({
                url: '@Url.Content("~/SystemRestore/ExecuteRestore")',
                data: {
                    'computerName': $computerName,
                    'sequenceNumber': $sequenceNumber
                },
                success: function (result) {
                    $('#responseMessages').html(result)
                },
                error: function (result) {
                    $('#responseMessages').html(result.responseText);
                }

            });

    });
</script>

FalconOrchestrator.Web/Areas/Forensics/Views/SystemRestore/_RestorePoints.cshtml
@model IEnumerable<FalconOrchestrator.Forensics.SystemRestorePoint>
@Html.Partial("_RestoreModal")
@Html.Partial("_RecoverModal")
<table id="datatable" class="table table-bordered table-hover dt-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Creation Time (UTC)")
            </th>
            <th>
                @Html.DisplayName("Description")
            </th>
            <th class="center-align">
                @Html.DisplayName("Sequence Number")
            </th>
            <th class="center-align">
                @Html.DisplayName("Event Type")
            </th>
            <th class="center-align">
                @Html.DisplayName("Restore Point Type")
            </th>`
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model)
            {
            <tr>
                <td>
                    @line.CreationTimeDateTime
                </td>
                <td>
                    @line.Description
                </td>
                <td class="center-align">
                    @line.SequenceNumber
                </td>
                <td class="center-align">
                    @line.EventType
                </td>
                <td class="center-align">
                    @line.RestorePointType
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/jquery.dataTables.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/dataTables.bootstrap.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/dataTables.responsive.js")"></script>
<script>
    $(document).ready(function () {

        $('#execute-restore').on("click", "#run-restore", function () {
            $('#restoreModal').modal('show');
        });

        $('#recover-data').on("click", "#run-recovery", function () {
            $('#recoverModal').modal('show');
        });

        var $table = $('#datatable').dataTable({
            "order": [[0, "dsc"]],
            "pagingType": "simple_numbers",
        });

        $('#datatable tbody').on('click', 'tr', function () {
            if ($(this).hasClass('active')) {
                $(this).removeClass('active');
                $('#run-restore').detach();
                $('#run-recovery').detach();
            }
            else {
                $table.$('tr.active').removeClass('active');
                $(this).addClass('active');
                if ($('#run-restore').length == 0) {
                    $('#execute-restore').append("<a href=\"#\" id=\"run-restore\" class=\"btn btn-primary btn-success\"><i class=\"fa fa-refresh\"></i> Restore</a>");
                }
                if ($('#run-recovery').length == 0) {
                    $('#recover-data').append("<a href=\"#\" id=\"run-recovery\" class=\"btn btn-primary btn-success\"><i class=\"fa fa-database\"></i> Recover</a>");
                }
            }
        });
    });

</script>
<link href="@Url.Content("~/Content/DataTables-1.10.4/css/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/DataTables-1.10.4/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

FalconOrchestrator.Web/Areas/Forensics/Views/SystemRestore/_ShadowCopyData.cshtml
@model IEnumerable<FalconOrchestrator.Forensics.FileMetadata>
<hr />
<h1>Shadow Copy Storage</h1>
<br />
<p>
    The shadow copy has now been mounted to the root of the primary file system in a directory titled shadow.  You can browse the files and select those you want to recover.
    This will copy the file back to the main file system where it was originally stored when the restore point was created.  If a file already exists with that name, it will be overwritten. 
    You can recover individual files or entire directories. To navigate the filesystem simply double click on a row within the table.
</p>
<br />
<p>
    These files are based off the shadow copy located at <b>@ViewBag.DeviceObject.Replace("\\\\", "\\")</b>
</p>
<p>
    Current active directory <b>@ViewBag.Path</b>
</p>
<br />
<div id="recoveryMessages"></div>
<br />
<table id="datatable2" class="table table-hover table-bordered dt-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("Extension")
            </th>
            <th>
                @Html.DisplayName("Length (Bytes)")
            </th>
            <th>
                @Html.DisplayName("Attributes")
            </th>
            <th class="center-align">
                @Html.DisplayName("Creation Time")
            </th>
            <th class="center-align">
                @Html.DisplayName("Last Access Time")
            </th>
            <th class="center-align">
                @Html.DisplayName("Last Modification Time")
            </th>
            <th>
                @Html.DisplayName("Full Path")
            </th>
            <th>
                @Html.DisplayName("Action")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr id="@item.FullName.Replace(" ","-").Replace("\\","-").Replace("(","-").Replace(")","-")">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Extension)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Attributes)
                </td>
                <td class="center-align">
                    @Html.DisplayFor(modelItem => item.CreationTime)
                </td>
                <td class="center-align">
                    @Html.DisplayFor(modelItem => item.LastAccessTime)
                </td>
                <td class="center-align">
                    @Html.DisplayFor(modelItem => item.LastWriteTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td class="center-align">
                    @Ajax.FormattedActionLink(string.Format("<i class='fa fa-copy'></i> Recover"), "RecoverFile", "SystemRestore", new { computerName = @ViewBag.ComputerName, source = @item.FullName, attributes = @item.Attributes }, new AjaxOptions { HttpMethod = "GET", OnFailure = "recoveryFailure", OnSuccess = "recoverySuccess" }, new { @class = "btn btn-default btn-success btn-sm" })
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/jquery.dataTables.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/dataTables.bootstrap.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/DataTables-1.10.4/dataTables.responsive.js")"></script>
<script>

    function recoverySuccess(data) {
        $('#recoveryMessages').append(data);
    }

    function recoveryFailure(data) {
        $('#recoveryMessages').append(data.responseText);
    }

    $(document).ready(function () {
        var $table = $('#datatable2').DataTable({
            "order": [[0, "asc"]],
            "pagingType": "simple_numbers",
            "columnDefs": [{ "className": "hidden", "targets": [7, 1, 2] }]
        });

        var $computerName = $('#targetComputerName').val();

        $('#datatable2 tbody').on('dblclick', 'tr', function () {
            var $attributes = $(this).find('td:eq(3)').text();
            var $deviceObject = '@ViewBag.DeviceObject';

            if ($attributes.indexOf("Directory") >= 0)
            {
                $(this).addClass('active');
                var $path = $(this).find('td:eq(7)').text();
                $.ajax({
                    url: '@Url.Content("~/SystemRestore/BrowserRefresh")',
                    data: {
                        'computerName': $computerName,
                        'path': $.trim($path),
                        'deviceObject': $deviceObject
                    },
                    success: function (result) {
                        $('#shadow-storage').html(result);
                    },
                    error: function(result)
                    {
                        $('#recoveryMessages').html(result.responseText);
                    }
                })
           }
        });
    });
</script>
<link href="@Url.Content("~/Content/DataTables-1.10.4/css/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/DataTables-1.10.4/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />